config/routes.rb
Rails.application.routes.draw do
  resources :lposts
  root "lposts#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lpost.rb
class Lpost < ApplicationRecord
	mount_uploader :cover, CoverUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/lposts_controller.rb
class LpostsController < ApplicationController
  before_action :set_lpost, only: [:show, :edit, :update, :destroy]

  # GET /lposts
  # GET /lposts.json
  def index
    @lposts = Lpost.all
  end

  # GET /lposts/1
  # GET /lposts/1.json
  def show
  end

  # GET /lposts/new
  def new
    @lpost = Lpost.new
  end

  # GET /lposts/1/edit
  def edit
  end

  # POST /lposts
  # POST /lposts.json
  def create
    @lpost = Lpost.new(lpost_params)

    respond_to do |format|
      if @lpost.save
        format.html { redirect_to @lpost, notice: 'Lpost was successfully created.' }
        format.json { render :show, status: :created, location: @lpost }
      else
        format.html { render :new }
        format.json { render json: @lpost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lposts/1
  # PATCH/PUT /lposts/1.json
  def update
    respond_to do |format|
      if @lpost.update(lpost_params)
        format.html { redirect_to @lpost, notice: 'Lpost was successfully updated.' }
        format.json { render :show, status: :ok, location: @lpost }
      else
        format.html { render :edit }
        format.json { render json: @lpost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lposts/1
  # DELETE /lposts/1.json
  def destroy
    @lpost.destroy
    respond_to do |format|
      format.html { redirect_to lposts_url, notice: 'Lpost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lpost
      @lpost = Lpost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lpost_params
      params.require(:lpost).permit(:tittle, :description, :location, :Contact, :cover)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lposts_helper.rb
module LpostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lnf</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lposts/_form.html.erb
<%= form_for(lpost) do |f| %>
  <% if lpost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lpost.errors.count, "error") %> prohibited this lpost from being saved:</h2>

      <ul>
      <% lpost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tittle %>
    <%= f.text_field :tittle %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :location %>
    <%= f.text_field :location %>
  </div>

  <div class="field">
    <%= f.label :Contact %>
    <%= f.text_field :Contact %>
  </div>

  <div class="field">
    <%= f.label :cover %>
    <%= f.file_field :cover %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lposts/edit.html.erb
<h1>Editing Lpost</h1>

<%= render 'form', lpost: @lpost %>

<%= link_to 'Show', @lpost %> |
<%= link_to 'Back', lposts_path %>

app/views/lposts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lposts</h1>

<table>
  <thead>
    <tr>
      <th>Tittle</th>
      <th>Description</th>
      <th>Location</th>
      <th>Contact</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lposts.each do |lpost| %>
      <tr>
        <td><%= lpost.tittle %></td>
        <td><%= lpost.description %></td>
        <td><%= lpost.location %></td>
        <td><%= lpost.Contact %></td>
        <td><%= link_to 'Show', lpost %></td>
        <td><%= link_to 'Edit', edit_lpost_path(lpost) %></td>
        <td><%= link_to 'Destroy', lpost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lpost', new_lpost_path %>

app/views/lposts/new.html.erb
<h1>New Lpost</h1>

<%= render 'form', lpost: @lpost %>

<%= link_to 'Back', lposts_path %>

app/views/lposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tittle:</strong>
  <%= @lpost.tittle %>
</p>

<p>
  <strong>Description:</strong>
  <%= @lpost.description %>
</p>

<p>
  <strong>Location:</strong>
  <%= @lpost.location %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @lpost.Contact %>
</p>

<p>
  <%= image_tag(@lpost.cover) %>
</p>

<%= link_to 'Edit', edit_lpost_path(@lpost) %> |
<%= link_to 'Back', lposts_path %>